import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "pbq-exercises.ts"
t = OUT.read_text(encoding="utf-8")
idx = t.find("export const pbqExercises")
idx = t.find("= [", idx)
if idx < 0: print("ERROR: = [ not found"); exit(1)
idx = t.find("[", idx)
depth = 0
for i in range(idx, len(t)):
    if t[i] == "[": depth += 1
    elif t[i] == "]":
        depth -= 1
        if depth == 0:
            existing = json.loads(t[idx:i+1])
            break
print(f"Found {len(existing)} existing")
new = []
new.append({"id":"pbq-log-gen-bruteforce","domain":"Security Operations","type":"investigation","title":"Log Gen: Brute Force","difficulty":"intermediate","timeLimitSeconds":240,"role":"SOC Analyst","scenario":"Le SIEM affiche les evenements suivants. Analyse et reponds.","objective":"Identifier brute force + compromission admin.","logs":[{"time":"10:01","source":"VPN-GW","event":"4625 failed login user=admin src=185.22.10.8"},{"time":"10:01","source":"VPN-GW","event":"4625 failed login user=admin src=185.22.10.8"},{"time":"10:01","source":"VPN-GW","event":"4625 failed login user=admin src=185.22.10.8"},{"time":"10:01","source":"VPN-GW","event":"4624 successful login user=admin src=185.22.10.8"},{"time":"10:01","source":"DC01","event":"4672 special privileges user=admin"},{"time":"10:01","source":"DC01","event":"4720 account created user=backdoor_svc"}],"tasks":[{"id":"t1","label":"Type","question":"Type d attaque?","choices":["Brute force + admin compromise","DDoS","Insider threat","Phishing"],"correctAnswer":0,"explanation":"4625 multiples puis 4624 meme IP + privileges + nouveau compte."},{"id":"t2","label":"Severite","question":"Severite?","choices":["Low","Medium","High","Critical"],"correctAnswer":2,"explanation":"Compromission admin = High."},{"id":"t3","label":"Action","question":"Action immediate?","choices":["Disable account + block IP + revoke sessions","Reboot DC","Email","Attendre"],"correctAnswer":0,"explanation":"Contenir: desactiver, bloquer IP, revoquer."},{"id":"t4","label":"IOCs","question":"IOCs?","choices":["4625 multiple + 4624 same IP + 4672 + 4720","Login normal","DNS standard","Web traffic"],"correctAnswer":0,"explanation":"4625 multiples puis 4624 meme IP + privileges + compte cree."},{"id":"t5","label":"Mitigation","question":"Mitigation?","choices":["MFA + account lockout + PAW + alerting","Rien","Plus de RAM","Telnet"],"correctAnswer":0,"explanation":"MFA, lockout, PAW, alerting groupes admin."}],"scoring":{"max":100,"rules":[]}})
new.append({"id":"pbq-log-gen-dnstunnel","domain":"Security Operations","type":"investigation","title":"Log Gen: DNS Tunneling","difficulty":"advanced","timeLimitSeconds":240,"role":"SOC Analyst","scenario":"Le monitoring DNS montre un trafic anormal. Analyse.","objective":"Identifier exfiltration par tunnel DNS.","logs":[{"time":"10:00","source":"DNS-SRV","event":"query=ajsd9283.company-data.attacker.com type=TXT"},{"time":"10:01","source":"DNS-SRV","event":"query=ksla7772.company-data.attacker.com type=TXT"},{"time":"10:02","source":"DNS-SRV","event":"query=zzx99182.company-data.attacker.com type=TXT"},{"time":"10:03","source":"DNS-SRV","event":"bytes_out_dns=950MB (baseline:5MB)"},{"time":"10:04","source":"DNS-SRV","event":"query=plm88219.company-data.attacker.com type=TXT"},{"time":"10:05","source":"FW-EDGE","event":"outbound DNS volume 200x baseline"}],"tasks":[{"id":"t1","label":"Type","question":"Type d attaque?","choices":["DNS tunneling / exfiltration","DDoS","SQLi","XSS"],"correctAnswer":0,"explanation":"TXT queries massives + volume DNS anormal."},{"id":"t2","label":"Severite","question":"Severite?","choices":["Low","Medium","High","Critical"],"correctAnswer":2,"explanation":"Exfiltration = High."},{"id":"t3","label":"IOCs","question":"IOCs?","choices":["DNS TXT queries + volume anormal + domaine suspect","HTTP normal","Ping","SSH"],"correctAnswer":0,"explanation":"TXT queries + volume 200x + domaine suspect."},{"id":"t4","label":"Action","question":"Action immediate?","choices":["Block domain + inspect DNS + isolate host","Reboot DNS","Attendre","Ajouter RAM"],"correctAnswer":0,"explanation":"Bloquer domaine, inspecter DNS, isoler hote."},{"id":"t5","label":"Mitigation","question":"Mitigation?","choices":["DNS filtering + DLP + egress monitoring","Rien","Desactiver DNS","Telnet"],"correctAnswer":0,"explanation":"Filtrage DNS, DLP, surveillance sortante."}],"scoring":{"max":100,"rules":[]}})
new.append({"id":"pbq-sprint-001","domain":"Security Architecture","type":"timed_config","title":"Sprint: Acces Distant (4 min)","difficulty":"intermediate","timeLimitSeconds":240,"role":"Security Engineer","scenario":"Configure un acces distant securise en 4 minutes.","objective":"Identifier les composants essentiels sous pression.","prompt":"Configure a secure remote access solution in 4 minutes.","requirements":["No direct SSH from Internet.","MFA required.","Logs centralized.","IT admins only."],"steps":[{"id":"s1","condition":"VPN or ZTNA access first","points":25,"explanation":"Pas de SSH direct. VPN/ZTNA obligatoire."},{"id":"s2","condition":"MFA enabled","points":20,"explanation":"MFA obligatoire."},{"id":"s3","condition":"Jump server / bastion host","points":20,"explanation":"Bastion vers serveurs internes."},{"id":"s4","condition":"SSH only from jump server","points":15,"explanation":"SSH uniquement depuis le bastion."},{"id":"s5","condition":"Logs to SIEM","points":10,"explanation":"Logs centralises SIEM."},{"id":"s6","condition":"RBAC IT admins only","points":10,"explanation":"Acces RBAC admins IT."}],"scoring":{"max":100,"rules":[]}})
new.append({"id":"pbq-cloud-shared","domain":"Security Architecture","type":"investigation","title":"Niveau 4: Cloud Shared Responsibility","difficulty":"simulation","timeLimitSeconds":300,"role":"Cloud Security Architect","scenario":"Migration cloud hybride. Determine les responsabilites.","objective":"Maitriser le modele de responsabilite partagee.","logs":[{"time":"Phase 1","source":"Architecture","event":"App web migree vers IaaS (VM Linux)"},{"time":"Phase 2","source":"Architecture","event":"DB migree vers PaaS (DBaaS)"},{"time":"Phase 3","source":"Architecture","event":"Messagerie migree vers SaaS (O365)"},{"time":"Phase 4","source":"Architecture","event":"Stockage objets migre vers IaaS (S3)"}],"tasks":[{"id":"c1","label":"IaaS-OS","question":"Qui securise l OS de la VM IaaS?","choices":["Le client (vous)","Le fournisseur","Personne","Les deux"],"correctAnswer":0,"explanation":"IaaS: client gere OS, apps, donnees."},{"id":"c2","label":"PaaS-DB","question":"Qui patche la DB PaaS?","choices":["Le client","Le fournisseur","Personne","Un tiers"],"correctAnswer":1,"explanation":"PaaS: fournisseur gere plateforme et patching."},{"id":"c3","label":"SaaS-MFA","question":"Qui configure MFA sur O365?","choices":["Le client","Microsoft","Personne","Les deux"],"correctAnswer":0,"explanation":"SaaS: client gere acces et MFA."},{"id":"c4","label":"Stockage","question":"Qui gere le chiffrement des donnees?","choices":["Le client","Le fournisseur","Personne","Automatique"],"correctAnswer":0,"explanation":"Client responsable du chiffrement."},{"id":"c5","label":"Controle","question":"Quel modele donne le plus de controle?","choices":["IaaS","PaaS","SaaS","Serverless"],"correctAnswer":0,"explanation":"IaaS = max controle + max responsabilite."}],"scoring":{"max":100,"rules":[]}})
all_ex = existing + new
hdr = "import type { FirewallPBQ, InvestigationPBQ, PBQExercise, RackVLANPBQ, SIEMPBQ, TimedConfigPBQ, TopologyPBQ } from './pbq';\n\n"
body = "export const pbqExercises: PBQExercise[] = " + json.dumps(all_ex, indent=2, ensure_ascii=False) + ";\n"
OUT.write_text(hdr + body, encoding="utf-8")
print(f"OK: {len(all_ex)} PBQs ({len(existing)}+{len(new)})")
for e in new: print(f"  + {e['id']}")
